version: '2'
services:
    emsweb-app:
        image: emsweb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://emsweb-mysql:3306/emsweb?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    emsweb-mysql:
        extends:
            file: mysql.yml
            service: emsweb-mysql
